Repository Rocketseat/adonis-bull, pull requests merged in 2021-02, with the labels that each got.

#68 ci: Fix coveralls error when running on CI
  .github/workflows/coveralls.yml
  package.json
  yarn.lock
Labels: type: ci

#47 chore(readme): adding event information to the documentation
  README.md
Labels: type: documentation

#72 fix: Use handle method by instance
  src/BullManager.ts
Labels: kind: bug
