Repository Rocketseat/adonis-bull, pull requests merged in 2021-01, with the labels that each got.

#52 ci: Stop running tests on Node.js 8
  .github/workflows/nodejs.yml
Labels: type: ci

#54 chore: Add OSS guidelines
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  LICENSE.md
  README.md
Labels: type: documentation, type: meta

#51 chore: Add Prettier
  .editorconfig
  .eslintrc.js
  .prettierrc
  japaFile.js
  package.json
  providers/Bull.js
  providers/Command.js
  src/Commands/Listen.js
  src/Queue.js
  test/functional/app/SomeJob.js
  test/functional/providers.spec.js
  test/functional/start/jobs.js
  test/unit/queue.spec.js
  yarn.lock
Labels: dependencies

#57 feat: Add test and provider improvements
  .nycrc
  README.md
  adonis-typings/bull.ts
  src/BullManager.ts
  test-helpers/index.ts
  test/functional/app/Jobs/SomeJob.ts
  test/functional/providers.spec.ts
  test/functional/start/jobs.ts
  test/unit/queue.spec.ts
Labels: type: core

#58 feat: add make exception command
  README.md
  adonis-typings/bull.ts
  commands/MakeException.ts
  commands/index.ts
  src/BullManager.ts
  templates/handler.txt
Labels: type: core

#55 chore: Configure commitlint and lint-staged
  package.json
  yarn.lock
Labels: dependencies

#56 ci: Create commit and lint workflows
  .github/workflows/commit.yml
  .github/workflows/lint.yml
Labels: type: ci

#61 release: Adonis v5 alpha
  .eslintrc.js
  .github/CODEOWNERS
  .gitignore
  .npmrc
  .nycrc
  README.md
  adonis-typings/bull.ts
  adonis-typings/exception-handler.ts
  adonis-typings/index.ts
  commands/Listen.ts
  commands/MakeException.ts
  commands/MakeJob.ts
  commands/index.ts
  instructions.ts
  japaFile.js
  package.json
  providers/Bull.js
  providers/BullProvider.ts
  providers/Command.js
  src/BullExceptionHandler.ts
  src/BullManager.ts
  src/Commands/Listen.js
  src/Queue.js
  templates/bull.txt
  templates/config.txt
  templates/contract.txt
  templates/handler.txt
  templates/job.txt
  templates/start.txt
  test-helpers/index.ts
  test/functional/app/SomeJob.js
  test/functional/providers.spec.js
  test/functional/providers.spec.ts
  test/functional/start/jobs.js
  test/unit/queue.spec.js
  test/unit/queue.spec.ts
  tsconfig.json
  yarn.lock
Labels: type: core alpha, type: feature request

#60 docs: Add note about Adonis v5
  README.md
Labels: type: documentation
